### PR TITLE
Fix for #39.

### PR DESCRIPTION
**Pull request by xpe**
I think that the upgrade from jClouds 1.4.2 to 1.5.1 in the previous
commit (9d6e47b7) made a change in how `.createSecurityGroupInRegion`
works (see security.clj).

### CODE REVIEW

**Comment by lorcan** [comment]
This also fixed the issue for me. Thanks :-)
Can we get this request pulled in?

**Comment by msegel** [comment]
Hi, ran in to the same problem... found the fix in lorcan's branch (which looks like xpe found first)... 
What does it take to get it implemented in the main branch? 

Looks like it was fixed 2 months ago? 

Thx

**Comment by 256BitChris** [comment]
Can we please merge this in?  As it stands, the master branch is unusable without this fix.  I had to merge in @lorcan 's fix to get this to work.

**Comment by 256BitChris** [comment]
Thanks so much!!

**Comment by xpe** [comment]
@tbatchelli Thank you!

**Pull request merged**
