### PR TITLE
Update Ubuntu

### PR DESCRIPTION
**Pull request by adsummos**
The 10.10 Ubuntu repo is no longer available. I updated the AMIs and fixed an installation issue with ZMQ

### CODE REVIEW

**Comment by jeroenvandijk** [comment]
Thanks @adsummos . This fixed my Elephantdb deployment https://github.com/jeroenvandijk/elephantdb-deploy/commit/f55a31d612da88475964465ebfa2a3018e84b868

**Comment by dandroid88** [comment]
This definitly helped me with the 10.10 repo issues however now I have a problem attaching to clusters.  When I run deploy it seems to get the instances up and running but I end up with an issue where attach fails with a NullPointer issue. http://pastebin.com/1LV3XVNj

**Comment by adsummos** [comment]
did you ever have it working or are you trying to get it working for the first time? I don't have any problems attaching to the cluster

**Comment by dandroid88** [comment]
I have had success getting a cluster up however I haven't been able to actually attach to that cluster completely (with the storm ui and ganglia forwarded).  It however did get far enough that I was able to submit topologies.

**Pull request closed without merging**
