### PR TITLE
Update to lein 2

### PR DESCRIPTION
**Pull request by travis**
Note that this changes the deploy command from

lein run :deploy --start --name mycluster --release {release version}

to

lein deploy-storm --start --name mycluster --release {release version}

### CODE REVIEW

**Comment by bruceadams** [comment]
I very much like the idea of upgrading to Leiningen 2. It seems wrong that storm-deploy then goes and installs Leiningen 1.5.2 on the nodes, see [crate/leiningen.clj](https://github.com/nathanmarz/storm-deploy/blob/master/src/clj/backtype/storm/crate/leiningen.clj#L7).

Once Leiningen 2 is released (likely this month), we should upgrade Leiningen both for the user and on the nodes.

**Comment by avocade** [comment]
Getting this using latest pull and leiningen 2.0.0 when using the CLI command above and the changed `project.clj`:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/tools/logging__init.class or clojure/tools/logging.clj on classpath:  (provision.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.load(Compiler.java:5857)
    at clojure.lang.RT.loadResourceScript(RT.java:340)
    at clojure.lang.RT.loadResourceScript(RT.java:331)
    at clojure.lang.RT.load(RT.java:409)
    at clojure.lang.RT.load(RT.java:381)
    at clojure.core$load$fn__4511.invoke(core.clj:4905)
    at clojure.core$load.doInvoke(core.clj:4904)
    at clojure.lang.RestFn.invoke(RestFn.java:409)
    at clojure.core$load_one.invoke(core.clj:4729)
    at clojure.core$load_lib.doInvoke(core.clj:4766)
    at clojure.lang.RestFn.applyTo(RestFn.java:143)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$load_libs.doInvoke(core.clj:4800)
    at clojure.lang.RestFn.applyTo(RestFn.java:138)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$require.doInvoke(core.clj:4869)
    at clojure.lang.RestFn.invoke(RestFn.java:409)
    at user$eval1.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    at clojure.lang.Compiler.eval(Compiler.java:5414)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$null_opt.invoke(main.clj:279)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:422)
    at clojure.lang.Var.invoke(Var.java:369)
    at clojure.lang.AFn.applyToHelper(AFn.java:165)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/logging__init.class or clojure/tools/logging.clj on classpath: 
    at clojure.lang.RT.load(RT.java:412)
    at clojure.lang.RT.load(RT.java:381)
    at clojure.core$load$fn__4511.invoke(core.clj:4905)
    at clojure.core$load.doInvoke(core.clj:4904)
    at clojure.lang.RestFn.invoke(RestFn.java:409)
    at clojure.core$load_one.invoke(core.clj:4729)
    at clojure.core$load_lib.doInvoke(core.clj:4766)
    at clojure.lang.RestFn.applyTo(RestFn.java:143)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$load_libs.doInvoke(core.clj:4800)
    at clojure.lang.RestFn.applyTo(RestFn.java:138)
    at clojure.core$apply.invoke(core.clj:544)
    at clojure.core$use.doInvoke(core.clj:4880)
    at clojure.lang.RestFn.invoke(RestFn.java:552)
    at backtype.storm.provision$eval5$loading__4410__auto____6.invoke(provision.clj:1)
    at backtype.storm.provision$eval5.invoke(provision.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    ... 32 more
```

On Mac OS X 10.8.2.

**Comment by aaronharnly** [comment]
+1 for this change. The quick-start instructions (https://github.com/nathanmarz/storm-deploy/wiki) link to the lein stable version, which is now at version 2.1.1. Hence the instructions, as written, don't work without this PR.

The instructions should link to a known-good version of lein, or this PR should be accepted to keep up with lein 2 – or, probably, both!

**Comment by jasonjckn** [comment]
Who's tested this diff and it worked fine? 
I don't use storm on ec2 anymore, so it's a little harder for me to test things, but i can merge it in.

**Comment by jasonjckn** [comment]
looking at the code again, it's a pretty straightforward.

**Comment by travis** [comment]
hey - I tested this at the time, but it's been a bit. will take a look right now...

**Comment by jasonjckn** [comment]
if you could merge in master, repush that would be helpful.

**Comment by travis** [comment]
ok - merged and brought up a cluster. It ended up failing to configure the instances, but I'm pretty sure that's because my ssh keys aren't set up right at the moment. Didn't see the stacktrace reported above.

It'd probably be good if someone else tested this too - I don't actually use storm-deploy day to day. 

I agree with the comment above re: updating the lein we install on instances, but don't think that's in scope for this PR - it should definitely be done by someone who's actually using this.

**Comment by gworley3** [comment]
i will give it a try and report back; i use an ec2 storm cluster and regularly bring up new temp ones for testing, so i'd be happy to give it a try using lein2.

**Comment by gworley3** [comment]
okay, i can confirm that this works with lein 2.0.0

**Comment by jasonjckn** [comment]
thanks!

**Pull request merged**
