### PR TITLE
Fixed two SEVERE bugs (build breakers in fact) in the storm build portion of deploy script

### PR DESCRIPTION
**Pull request by txbm**
NOTE: The current version of storm-deploy is currently BROKEN by the bugs for which fixes this pull request contains. 

To be clear, the current version of storm-deploy must not have been tested because the following two issues are currently on the master branch and should affect ANY environment:

1) The pallet code that executes the call to the build_release.sh script utilizes the (sh) function which obviously will not work because BASH is required to execute Storm's build_release script.

2) The (get-release) function does not properly build the BASH conditional which checks for the release version specified on the CLI and simply ignores it even if it is present, resulting in an automatic install attempt of whatever is on the master branch of the Storm repo. This is obviously bad news since the bleeding edge is usually not desired in production.

I have included fixes for both of these issues and thoroughly tested them from a completely scratch deployment. I urge this request to be merged in as quickly as possible since I cannot see the current version working under any circumstances.

### CODE REVIEW

**Comment by ghost** [comment]
Hi Peter
We are working on implementing vmfest, which will make it much easier to debug the system. In the meantime, I thank you for your pull request. I will take a look at it tonight.

**Comment by txbm** [comment]
@jasonjckn Sorry-- implemented in hurry since I was concerned about breakage. I will refactor using binds and push the change in a few minutes.

@KasperMadsen vmfest sounds great, I'll keep that in mind when making future contributions. Would also love to see a separate branch with the beginnings of that so I can help out.

**Comment by txbm** [comment]
All set, let me know if you need anything else before merge.

**Comment by jasonjckn** [comment]
thanks again.

**Comment by txbm** [comment]
anytime :smile:

**Pull request merged**
